/**
 * generateTsAbis.ts - 生成前端 ABI 类型定义脚本
 *
 * ⚠️ 重要：除非你知道自己在做什么，否则不要修改或删除此脚本
 *
 * 功能：
 * 1. 读取 deployments/ 目录下的所有部署信息
 * 2. 提取每个合约的 ABI、地址、继承函数等
 * 3. 生成 TypeScript 类型定义文件
 * 4. 输出到 packages/nextjs/contracts/deployedContracts.ts
 *
 * 触发时机：
 * - 每次运行 `yarn deploy` 后自动执行
 * - 在 hardhat.config.ts 的 task("deploy") 中被调用
 *
 * 作用：
 * - 前端 Scaffold-ETH hooks 需要这个文件来获取合约信息
 * - abitype 会根据 ABI 自动推导 TypeScript 类型
 * - 确保前端始终使用最新的合约接口
 */

import * as fs from "fs";
import prettier from "prettier"; // 用于格式化生成的代码
import { DeployFunction } from "hardhat-deploy/types";

// 生成文件的顶部注释
// 警告用户：这是自动生成的文件，不要手动修改
const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

// 部署信息目录（hardhat-deploy 插件生成）
const DEPLOYMENTS_DIR = "./deployments";
// 编译产物目录（Hardhat 编译器生成）
const ARTIFACTS_DIR = "./artifacts";

/**
 * 获取目录下的所有子目录名称
 * @param path - 目标目录路径
 * @returns 子目录名称数组
 *
 * 示例：getDirectories("./deployments") -> ["hardhat", "sepolia", "mainnet"]
 */
function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true }) // 读取目录，返回 Dirent 对象数组
    .filter(dirent => dirent.isDirectory()) // 只保留目录
    .map(dirent => dirent.name); // 提取目录名
}

/**
 * 获取目录下的所有合约名称（从 JSON 文件名提取）
 * @param path - 目标目录路径
 * @returns 合约名称数组
 *
 * 示例：getContractNames("./deployments/sepolia")
 *       -> ["YourContract", "NFTStaking"]（从 YourContract.json 提取）
 */
function getContractNames(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true }) // 读取目录
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json")) // 只保留 JSON 文件
    .map(dirent => dirent.name.split(".")[0]); // 提取文件名（去掉 .json）
}

/**
 * 获取合约继承的父合约列表
 * @param sources - 编译元数据中的源码映射
 * @param contractName - 合约名称
 * @returns 父合约文件名数组
 *
 * 作用：解析 Solidity 源码，提取继承关系
 * 示例：contract YourContract is Ownable, Pausable
 *       -> ["Ownable.sol", "Pausable.sol"]
 */
function getActualSourcesForContract(sources: Record<string, any>, contractName: string) {
  // 遍历所有源文件路径
  for (const sourcePath of Object.keys(sources)) {
    // 从路径中提取文件名（去掉 .sol）
    // 例如："contracts/YourContract.sol" -> "YourContract"
    const sourceName = sourcePath.split("/").pop()?.split(".sol")[0];

    if (sourceName === contractName) {
      // 找到目标合约的源码
      const contractContent = sources[sourcePath].content as string;

      // 使用正则表达式匹配继承声明
      // 匹配格式：contract ContractName is ParentContract1, ParentContract2 {
      const regex = /contract\s+(\w+)\s+is\s+([^{}]+)\{/;
      const match = contractContent.match(regex);

      if (match) {
        // match[2] 是继承部分，例如："Ownable, Pausable"
        const inheritancePart = match[2];

        // 分割并整理父合约名称
        const inheritedContracts = inheritancePart.split(",").map(contract => `${contract.trim()}.sol`);

        return inheritedContracts;
      }
      return []; // 没有继承关系
    }
  }
  return []; // 未找到合约
}

/**
 * 获取从父合约继承的函数映射
 * @param sources - 编译元数据中的源码映射
 * @param contractName - 合约名称
 * @returns 继承函数映射 { 函数名: 源文件路径 }
 *
 * 作用：标记哪些函数是从父合约继承的
 * 用途：前端可以区分自有函数和继承函数
 */
function getInheritedFunctions(sources: Record<string, any>, contractName: string) {
  // 获取父合约列表
  const actualSources = getActualSourcesForContract(sources, contractName);
  const inheritedFunctions = {} as Record<string, any>;

  // 遍历每个父合约
  for (const sourceContractName of actualSources) {
    // 在源码中查找父合约的文件路径
    const sourcePath = Object.keys(sources).find(key => key.includes(`/${sourceContractName}`));

    if (sourcePath) {
      // 从路径中提取合约名称
      const sourceName = sourcePath?.split("/").pop()?.split(".sol")[0];

      // 读取父合约的编译产物（包含 ABI）
      const { abi } = JSON.parse(fs.readFileSync(`${ARTIFACTS_DIR}/${sourcePath}/${sourceName}.json`).toString());

      // 遍历父合约的所有函数
      for (const functionAbi of abi) {
        if (functionAbi.type === "function") {
          // 记录函数名和来源
          inheritedFunctions[functionAbi.name] = sourcePath;
        }
      }
    }
  }

  return inheritedFunctions;
}

/**
 * 从 deployments 目录读取所有部署信息
 * @returns 按 chainId 组织的合约数据
 *
 * 返回格式：
 * {
 *   "31337": {  // chainId (hardhat 本地网络)
 *     "YourContract": {
 *       address: "0x5FbDB...",
 *       abi: [...],
 *       inheritedFunctions: { "owner": "contracts/Ownable.sol" },
 *       deployedOnBlock: 1
 *     }
 *   },
 *   "11155111": {  // chainId (sepolia 测试网)
 *     "YourContract": { ... }
 *   }
 * }
 */
function getContractDataFromDeployments() {
  // 检查 deployments 目录是否存在
  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    throw Error("At least one other deployment script should exist to generate an actual contract.");
  }

  const output = {} as Record<string, any>;

  // 获取所有网络目录（例如：hardhat, sepolia, mainnet）
  const chainDirectories = getDirectories(DEPLOYMENTS_DIR);

  for (const chainName of chainDirectories) {
    let chainId;
    try {
      // 读取 .chainId 文件获取链 ID
      // hardhat-deploy 会在每个网络目录下创建这个文件
      chainId = fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/.chainId`).toString();
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (error) {
      console.log(`No chainId file found for ${chainName}`);
      continue; // 跳过没有 chainId 的目录
    }

    // 存储当前链上的所有合约
    const contracts = {} as Record<string, any>;

    // 遍历当前网络目录下的所有合约
    for (const contractName of getContractNames(`${DEPLOYMENTS_DIR}/${chainName}`)) {
      // 读取合约的部署信息 JSON 文件
      // hardhat-deploy 会为每个部署的合约生成一个 JSON 文件
      const { abi, address, metadata, receipt } = JSON.parse(
        fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/${contractName}.json`).toString(),
      );

      // 提取继承的函数（如果有 metadata）
      const inheritedFunctions = metadata ? getInheritedFunctions(JSON.parse(metadata).sources, contractName) : {};

      // 组装合约数据
      contracts[contractName] = {
        address, // 合约地址
        abi, // 合约 ABI
        inheritedFunctions, // 继承的函数映射
        deployedOnBlock: receipt?.blockNumber, // 部署时的区块号
      };
    }

    // 以 chainId 为键存储合约数据
    output[chainId] = contracts;
  }

  return output;
}

/**
 * 生成 TypeScript 合约定义文件（主函数）
 *
 * 这个函数会：
 * 1. 从 deployments 目录读取所有部署信息
 * 2. 生成 TypeScript 代码
 * 3. 使用 Prettier 格式化代码
 * 4. 写入到前端的 contracts 目录
 *
 * 此脚本应该在部署完成后运行（hardhat.config.ts 中配置）
 */
const generateTsAbis: DeployFunction = async function () {
  // 目标目录：前端的 contracts 文件夹
  const TARGET_DIR = "../nextjs/contracts/";

  // 读取所有部署信息
  const allContractsData = getContractDataFromDeployments();

  // 生成文件内容：将合约数据转换为 TypeScript 对象字面量
  // 格式：31337: { YourContract: {...} }, 11155111: { YourContract: {...} }
  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  // 确保目标目录存在
  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR);
  }

  // 生成完整的 TypeScript 文件内容
  const tsFileContent = `${generatedContractComment} import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract"; \n\n
 const deployedContracts = {${fileContent}} as const; \n\n export default deployedContracts satisfies GenericContractsDeclaration`;

  // 使用 Prettier 格式化代码
  const formattedContent = await prettier.format(tsFileContent, {
    parser: "typescript", // 使用 TypeScript 解析器
  });

  // 写入文件
  fs.writeFileSync(`${TARGET_DIR}deployedContracts.ts`, formattedContent);

  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
};

// 导出函数供 hardhat-deploy 使用
export default generateTsAbis;
